apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: default-oadp
  namespace: openshift-adp
spec:
  backupLocations:
    - velero:
        config:
          profile: default
          region: ap-southeast-1
        credential:
          key: cloud
          name: cloud-credentials
        default: true
        objectStorage:
          bucket: <YOUR BUCKET NAME HERE>
          prefix: <FOLDER WHERE VELERO FILES WILL BE STORED>
        provider: aws
  configuration:
    restic:
      enable: true
    velero:
      defaultPlugins:
        - openshift
        - csi
        - aws
      resourceTimeout: 10m
  snapshotLocations:
    - velero:
        config:
          profile: default
          region: ap-southeast-1
        provider: aws
