apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipelines-oadp-role
rules:
  - apiGroups:
      - 'velero.io'
    resources:
      - backups
    verbs:
      - '*' # Used all verbs for testing + convenience purpose ONLY, please allocate the appropriate permissions on your environment!


