# Task 2: Retrieve Velero backup file from S3 and save into Tekton workspace
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: step2-backup-s3toworkspace
  namespace: pipeline-ns
spec:
  workspaces:
    - name: bucket-prefix
      mountPath: /sno
  params:
    - name: name-of-backup
    - name: namespace-to-backup
    - name: bucket-name
    - name: bucket-secret
  steps:
    - name: s3-to-workspace
      image: amazon/aws-cli
      envFrom:
        - secretRef:
            name: $(params.bucket-secret)
      command: ["/bin/bash", "-c"]
      args:
        - |-
          aws s3 sync s3://$(params.bucket-name)$(workspaces.bucket-prefix.path)/backups/$(params.name-of-backup)/ $(workspaces.bucket-prefix.path)/backups/$(params.name-of-backup)/
          aws s3 sync s3://$(params.bucket-name)$(workspaces.bucket-prefix.path)/restic/ $(workspaces.bucket-prefix.path)/restic/$(params.namespace-to-backup)/
