# Task 3: SCP files from Tekton workspace into local NFS server
# As pods are ephemeral by nature, we need to add the host fingerprint manually for every instance of a task pod (else the pipeline will fail due to permission issues).
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: step3-backup-workspacetonfs
spec:
  workspaces:
    - name: bucket-prefix
      mountPath: /sno
    - name: nfsserver.pem
      mountPath: /nfsserver.pem
  params:
    - name: name-of-backup
    - name: bucket-name
    - name: bucket-secret
    - name: ssh-fingerprint
    - name: nfs-user
    - name: nfs-server-ip
    - name: nfs-directory
  steps:
    - name: workspace-to-nfs
      image: quay.io/devfile/base-developer-image:ubi8-latest
      envFrom:
        - secretRef:
            name: $(params.bucket-secret)
      command: ["/bin/bash", "-c"]
      args:
        - |-
          mkdir ~/.ssh/
          echo "$(params.ssh-fingerprint)" > ~/.ssh/known_hosts
          scp -ri "$(workspaces.nfsserver.pem.path)/nfsserver.pem" $(workspaces.bucket-prefix.path)/ $(params.nfs-user)@$(params.nfs-server-ip):$(params.nfs-directory)
